name: CD
on:
  push:
    tags:
      - '*'

jobs:
  deploy-release-notes:
    name: Generate Release Notes
    runs-on: ubuntu-18.04
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Get the git tag from the environmental variables
      # It will used to tag the docker image
      - name: Get release tag
        id: get_tag
        run: echo ::set-output name=tag::"${GITHUB_REF#refs/tags/}"

      # Setup python 3.6
      - name: Setup python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      # Install dependencies of the releaseGen.py script
      - name: Install dependencies
        run: |
          python -m pip install \
            GitPython \
            PyGithub

      # Generate a release using the releaseGen.py script
      - name: Generate release notes
        env:
          REPO_SLUG: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.get_tag.outputs.tag }}
        run: python releaseGen.py
