name: C++ tests
on: push

jobs:
  cpp-tests:
    name: C++ tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch name
        id: branch_name
        env:
          VAR1: TEST
          BRANCH_NAME: ${{ github.head_ref }}
        shell: bash
        run: |
          echo VAR1 = $VAR1
          echo BRANCH_NAME = $BRANCH_NAME
          echo GITHUB_REF = $GITHUB_REF
          TRAVIS_BRANCH=${BRANCH_NAME:-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')}
          echo TRAVIS_BRANCH = $TRAVIS_BRANCH
          echo ::set-output name=branch::"$TRAVIS_BRANCH"
          
          
      - name: Read branch name
        run: echo Branch name = ${{ steps.branch_name.branch }}
        
      - name: Compile
        run: g++ -o test test.cpp
        shell: bash
      - name: upload binary
        uses: actions/upload-artifact@v1
        with:
          name: binary
          path: test
  cpp-tests-2:
    name: C++ test second
    runs-on: ubuntu-latest
    needs: cpp-tests
    steps:
      - name: download binary
        uses: actions/download-artifact@v2
        with:
          name: binary

      - name: Run
        run: chmod +x test && ./test
        shell: bash
  cpp-publish:
    name: C++ publish binary
    runs-on: ubuntu-latest
    needs: cpp-tests-2
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: echo ::set-output name=tags::"jesusvasquez333/test-push:${GITHUB_REF#refs/tags/}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
