name: C++ tests
on: push

jobs:
  cpp-tests:
    name: C++ tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile
        run: g++ -o test test.cpp
        shell: bash
      - name: upload binary
        uses: actions/upload-artifact@v1
        with:
          name: binary
          path: test
  cpp-tests-2:
    name: C++ test second
    runs-on: ubuntu-latest
    needs: cpp-tests
    steps:
      - name: download binary
        uses: actions/download-artifact@v2
        with:
          name: binary

      - name: Run
        run: chmod +x test && ./test
        shell: bash
  cpp-publish:
    name: C++ publish binary
    needs: cpp-tests-2
    #if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to docker hub
        run: echo "Docker push here"
        shell: bash

        #uses docker/build-push-action@v1
        #with:
        #  username: ${{ secrets.DOCKER_USERNAME }}
        #  password: ${{ secrets.DOCKER_PASSWORD }}
        #  repository: jesusvasquez333/test-push
        #  tag_with_ref: true
