name: python tests
on: push

jobs:
  python-tests:
    name: python tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Setup node environment 
        uses: actions/setup-node@v2
        with:
          node-version: '12'
    
      - name: Install dependencies
        run: |
          python -m pip install flake8-rst-docstrings flake8-sfs flake8-import-order    
          npm install github-release-notes@0.17.3 -g

      - name: Flake8 Checks
        run: flake8 --count python/
      
      - name: Run gren
        run: gren release
        
